// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"kratosEntContractService/internal/biz"
	"kratosEntContractService/internal/conf"
	"kratosEntContractService/internal/data"
	"kratosEntContractService/internal/server"
	"kratosEntContractService/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	data_Database := data.NewDatabaseConfig(confData)
	client, err := data.NewEntClient(data_Database)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(client, logger)
	if err != nil {
		return nil, nil, err
	}
	iContractRepo := data.NewContractRepo(dataData)
	iContractBiz := biz.NewContractService(iContractRepo)
	contractService := service.NewContractService(iContractBiz)
	grpcServer := server.NewGRPCServer(confServer, contractService, logger)
	//httpServer := server.NewHTTPServer(confServer, contractService, logger)
	app, err := newApp(logger, grpcServer, dataData)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return app, func() {
		cleanup()
	}, nil
}
