// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: contract/contract.proto

package contract

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Contract struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StudentCode          string                 `protobuf:"bytes,2,opt,name=student_code,json=studentCode,proto3" json:"student_code,omitempty"`
	FirstName            string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	MiddleName           string                 `protobuf:"bytes,5,opt,name=middle_name,json=middleName,proto3" json:"middle_name,omitempty"`
	Email                string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string                 `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	Gender               uint32                 `protobuf:"varint,8,opt,name=gender,proto3" json:"gender,omitempty"`
	Dob                  *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=dob,proto3" json:"dob,omitempty"`
	Address              string                 `protobuf:"bytes,10,opt,name=address,proto3" json:"address,omitempty"`
	Avatar               string                 `protobuf:"bytes,11,opt,name=avatar,proto3" json:"avatar,omitempty"`
	RoomId               string                 `protobuf:"bytes,12,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	IsActive             bool                   `protobuf:"varint,13,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Sign                 string                 `protobuf:"bytes,14,opt,name=sign,proto3" json:"sign,omitempty"`
	RegistryAt           *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=registry_at,json=registryAt,proto3" json:"registry_at,omitempty"`
	NotificationChannels uint32                 `protobuf:"varint,16,opt,name=notification_channels,json=notificationChannels,proto3" json:"notification_channels,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Contract) Reset() {
	*x = Contract{}
	mi := &file_contract_contract_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contract) ProtoMessage() {}

func (x *Contract) ProtoReflect() protoreflect.Message {
	mi := &file_contract_contract_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contract.ProtoReflect.Descriptor instead.
func (*Contract) Descriptor() ([]byte, []int) {
	return file_contract_contract_proto_rawDescGZIP(), []int{0}
}

func (x *Contract) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Contract) GetStudentCode() string {
	if x != nil {
		return x.StudentCode
	}
	return ""
}

func (x *Contract) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Contract) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Contract) GetMiddleName() string {
	if x != nil {
		return x.MiddleName
	}
	return ""
}

func (x *Contract) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Contract) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Contract) GetGender() uint32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *Contract) GetDob() *timestamppb.Timestamp {
	if x != nil {
		return x.Dob
	}
	return nil
}

func (x *Contract) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Contract) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Contract) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *Contract) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Contract) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

func (x *Contract) GetRegistryAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RegistryAt
	}
	return nil
}

func (x *Contract) GetNotificationChannels() uint32 {
	if x != nil {
		return x.NotificationChannels
	}
	return 0
}

type CreateContractRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	StudentCode          string                 `protobuf:"bytes,1,opt,name=student_code,json=studentCode,proto3" json:"student_code,omitempty"`
	FirstName            string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	MiddleName           string                 `protobuf:"bytes,4,opt,name=middle_name,json=middleName,proto3" json:"middle_name,omitempty"`
	Email                string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Phone                string                 `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	Gender               uint32                 `protobuf:"varint,7,opt,name=gender,proto3" json:"gender,omitempty"`
	Dob                  *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=dob,proto3" json:"dob,omitempty"`
	Address              string                 `protobuf:"bytes,9,opt,name=address,proto3" json:"address,omitempty"`
	Avatar               string                 `protobuf:"bytes,10,opt,name=avatar,proto3" json:"avatar,omitempty"`
	RoomId               string                 `protobuf:"bytes,11,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	IsActive             bool                   `protobuf:"varint,12,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Sign                 string                 `protobuf:"bytes,13,opt,name=sign,proto3" json:"sign,omitempty"`
	NotificationChannels uint32                 `protobuf:"varint,14,opt,name=notification_channels,json=notificationChannels,proto3" json:"notification_channels,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateContractRequest) Reset() {
	*x = CreateContractRequest{}
	mi := &file_contract_contract_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContractRequest) ProtoMessage() {}

func (x *CreateContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_contract_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContractRequest.ProtoReflect.Descriptor instead.
func (*CreateContractRequest) Descriptor() ([]byte, []int) {
	return file_contract_contract_proto_rawDescGZIP(), []int{1}
}

func (x *CreateContractRequest) GetStudentCode() string {
	if x != nil {
		return x.StudentCode
	}
	return ""
}

func (x *CreateContractRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateContractRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreateContractRequest) GetMiddleName() string {
	if x != nil {
		return x.MiddleName
	}
	return ""
}

func (x *CreateContractRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateContractRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateContractRequest) GetGender() uint32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *CreateContractRequest) GetDob() *timestamppb.Timestamp {
	if x != nil {
		return x.Dob
	}
	return nil
}

func (x *CreateContractRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateContractRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *CreateContractRequest) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *CreateContractRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *CreateContractRequest) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

func (x *CreateContractRequest) GetNotificationChannels() uint32 {
	if x != nil {
		return x.NotificationChannels
	}
	return 0
}

type CreateContractReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContractReply) Reset() {
	*x = CreateContractReply{}
	mi := &file_contract_contract_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContractReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContractReply) ProtoMessage() {}

func (x *CreateContractReply) ProtoReflect() protoreflect.Message {
	mi := &file_contract_contract_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContractReply.ProtoReflect.Descriptor instead.
func (*CreateContractReply) Descriptor() ([]byte, []int) {
	return file_contract_contract_proto_rawDescGZIP(), []int{2}
}

func (x *CreateContractReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateContractRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	StudentCode          *string                `protobuf:"bytes,2,opt,name=student_code,json=studentCode,proto3,oneof" json:"student_code,omitempty"`
	FirstName            *string                `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3,oneof" json:"first_name,omitempty"`
	LastName             *string                `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3,oneof" json:"last_name,omitempty"`
	MiddleName           *string                `protobuf:"bytes,5,opt,name=middle_name,json=middleName,proto3,oneof" json:"middle_name,omitempty"`
	Email                *string                `protobuf:"bytes,6,opt,name=email,proto3,oneof" json:"email,omitempty"`
	Phone                *string                `protobuf:"bytes,7,opt,name=phone,proto3,oneof" json:"phone,omitempty"`
	Gender               *uint32                `protobuf:"varint,8,opt,name=gender,proto3,oneof" json:"gender,omitempty"`
	Dob                  *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=dob,proto3" json:"dob,omitempty"`
	Address              *string                `protobuf:"bytes,10,opt,name=address,proto3,oneof" json:"address,omitempty"`
	Avatar               *string                `protobuf:"bytes,11,opt,name=avatar,proto3,oneof" json:"avatar,omitempty"`
	RoomId               *string                `protobuf:"bytes,12,opt,name=room_id,json=roomId,proto3,oneof" json:"room_id,omitempty"`
	IsActive             *bool                  `protobuf:"varint,13,opt,name=is_active,json=isActive,proto3,oneof" json:"is_active,omitempty"`
	Sign                 *string                `protobuf:"bytes,14,opt,name=sign,proto3,oneof" json:"sign,omitempty"`
	NotificationChannels *uint32                `protobuf:"varint,15,opt,name=notification_channels,json=notificationChannels,proto3,oneof" json:"notification_channels,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UpdateContractRequest) Reset() {
	*x = UpdateContractRequest{}
	mi := &file_contract_contract_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateContractRequest) ProtoMessage() {}

func (x *UpdateContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_contract_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateContractRequest.ProtoReflect.Descriptor instead.
func (*UpdateContractRequest) Descriptor() ([]byte, []int) {
	return file_contract_contract_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateContractRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateContractRequest) GetStudentCode() string {
	if x != nil && x.StudentCode != nil {
		return *x.StudentCode
	}
	return ""
}

func (x *UpdateContractRequest) GetFirstName() string {
	if x != nil && x.FirstName != nil {
		return *x.FirstName
	}
	return ""
}

func (x *UpdateContractRequest) GetLastName() string {
	if x != nil && x.LastName != nil {
		return *x.LastName
	}
	return ""
}

func (x *UpdateContractRequest) GetMiddleName() string {
	if x != nil && x.MiddleName != nil {
		return *x.MiddleName
	}
	return ""
}

func (x *UpdateContractRequest) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

func (x *UpdateContractRequest) GetPhone() string {
	if x != nil && x.Phone != nil {
		return *x.Phone
	}
	return ""
}

func (x *UpdateContractRequest) GetGender() uint32 {
	if x != nil && x.Gender != nil {
		return *x.Gender
	}
	return 0
}

func (x *UpdateContractRequest) GetDob() *timestamppb.Timestamp {
	if x != nil {
		return x.Dob
	}
	return nil
}

func (x *UpdateContractRequest) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *UpdateContractRequest) GetAvatar() string {
	if x != nil && x.Avatar != nil {
		return *x.Avatar
	}
	return ""
}

func (x *UpdateContractRequest) GetRoomId() string {
	if x != nil && x.RoomId != nil {
		return *x.RoomId
	}
	return ""
}

func (x *UpdateContractRequest) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

func (x *UpdateContractRequest) GetSign() string {
	if x != nil && x.Sign != nil {
		return *x.Sign
	}
	return ""
}

func (x *UpdateContractRequest) GetNotificationChannels() uint32 {
	if x != nil && x.NotificationChannels != nil {
		return *x.NotificationChannels
	}
	return 0
}

type UpdateContractReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateContractReply) Reset() {
	*x = UpdateContractReply{}
	mi := &file_contract_contract_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateContractReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateContractReply) ProtoMessage() {}

func (x *UpdateContractReply) ProtoReflect() protoreflect.Message {
	mi := &file_contract_contract_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateContractReply.ProtoReflect.Descriptor instead.
func (*UpdateContractReply) Descriptor() ([]byte, []int) {
	return file_contract_contract_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateContractReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteContractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteContractRequest) Reset() {
	*x = DeleteContractRequest{}
	mi := &file_contract_contract_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContractRequest) ProtoMessage() {}

func (x *DeleteContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_contract_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContractRequest.ProtoReflect.Descriptor instead.
func (*DeleteContractRequest) Descriptor() ([]byte, []int) {
	return file_contract_contract_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteContractRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteContractReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteContractReply) Reset() {
	*x = DeleteContractReply{}
	mi := &file_contract_contract_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteContractReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContractReply) ProtoMessage() {}

func (x *DeleteContractReply) ProtoReflect() protoreflect.Message {
	mi := &file_contract_contract_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContractReply.ProtoReflect.Descriptor instead.
func (*DeleteContractReply) Descriptor() ([]byte, []int) {
	return file_contract_contract_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteContractReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetContractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContractRequest) Reset() {
	*x = GetContractRequest{}
	mi := &file_contract_contract_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContractRequest) ProtoMessage() {}

func (x *GetContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_contract_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContractRequest.ProtoReflect.Descriptor instead.
func (*GetContractRequest) Descriptor() ([]byte, []int) {
	return file_contract_contract_proto_rawDescGZIP(), []int{7}
}

func (x *GetContractRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetContractReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contract      *Contract              `protobuf:"bytes,1,opt,name=contract,proto3" json:"contract,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContractReply) Reset() {
	*x = GetContractReply{}
	mi := &file_contract_contract_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContractReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContractReply) ProtoMessage() {}

func (x *GetContractReply) ProtoReflect() protoreflect.Message {
	mi := &file_contract_contract_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContractReply.ProtoReflect.Descriptor instead.
func (*GetContractReply) Descriptor() ([]byte, []int) {
	return file_contract_contract_proto_rawDescGZIP(), []int{8}
}

func (x *GetContractReply) GetContract() *Contract {
	if x != nil {
		return x.Contract
	}
	return nil
}

func (x *GetContractReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type IncludeExcludeString struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Includes      []string               `protobuf:"bytes,1,rep,name=includes,proto3" json:"includes,omitempty"`
	Excludes      []string               `protobuf:"bytes,2,rep,name=excludes,proto3" json:"excludes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncludeExcludeString) Reset() {
	*x = IncludeExcludeString{}
	mi := &file_contract_contract_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncludeExcludeString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncludeExcludeString) ProtoMessage() {}

func (x *IncludeExcludeString) ProtoReflect() protoreflect.Message {
	mi := &file_contract_contract_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncludeExcludeString.ProtoReflect.Descriptor instead.
func (*IncludeExcludeString) Descriptor() ([]byte, []int) {
	return file_contract_contract_proto_rawDescGZIP(), []int{9}
}

func (x *IncludeExcludeString) GetIncludes() []string {
	if x != nil {
		return x.Includes
	}
	return nil
}

func (x *IncludeExcludeString) GetExcludes() []string {
	if x != nil {
		return x.Excludes
	}
	return nil
}

type IncludeExcludeUint32 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Includes      []uint32               `protobuf:"varint,1,rep,packed,name=includes,proto3" json:"includes,omitempty"`
	Excludes      []uint32               `protobuf:"varint,2,rep,packed,name=excludes,proto3" json:"excludes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncludeExcludeUint32) Reset() {
	*x = IncludeExcludeUint32{}
	mi := &file_contract_contract_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncludeExcludeUint32) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncludeExcludeUint32) ProtoMessage() {}

func (x *IncludeExcludeUint32) ProtoReflect() protoreflect.Message {
	mi := &file_contract_contract_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncludeExcludeUint32.ProtoReflect.Descriptor instead.
func (*IncludeExcludeUint32) Descriptor() ([]byte, []int) {
	return file_contract_contract_proto_rawDescGZIP(), []int{10}
}

func (x *IncludeExcludeUint32) GetIncludes() []uint32 {
	if x != nil {
		return x.Includes
	}
	return nil
}

func (x *IncludeExcludeUint32) GetExcludes() []uint32 {
	if x != nil {
		return x.Excludes
	}
	return nil
}

type IncludeExcludeInt32 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Includes      []int32                `protobuf:"varint,1,rep,packed,name=includes,proto3" json:"includes,omitempty"`
	Excludes      []int32                `protobuf:"varint,2,rep,packed,name=excludes,proto3" json:"excludes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncludeExcludeInt32) Reset() {
	*x = IncludeExcludeInt32{}
	mi := &file_contract_contract_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncludeExcludeInt32) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncludeExcludeInt32) ProtoMessage() {}

func (x *IncludeExcludeInt32) ProtoReflect() protoreflect.Message {
	mi := &file_contract_contract_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncludeExcludeInt32.ProtoReflect.Descriptor instead.
func (*IncludeExcludeInt32) Descriptor() ([]byte, []int) {
	return file_contract_contract_proto_rawDescGZIP(), []int{11}
}

func (x *IncludeExcludeInt32) GetIncludes() []int32 {
	if x != nil {
		return x.Includes
	}
	return nil
}

func (x *IncludeExcludeInt32) GetExcludes() []int32 {
	if x != nil {
		return x.Excludes
	}
	return nil
}

type RequestTime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromTime      *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=from_time,json=fromTime,proto3" json:"from_time,omitempty"`
	ToTime        *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=to_time,json=toTime,proto3" json:"to_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestTime) Reset() {
	*x = RequestTime{}
	mi := &file_contract_contract_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestTime) ProtoMessage() {}

func (x *RequestTime) ProtoReflect() protoreflect.Message {
	mi := &file_contract_contract_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestTime.ProtoReflect.Descriptor instead.
func (*RequestTime) Descriptor() ([]byte, []int) {
	return file_contract_contract_proto_rawDescGZIP(), []int{12}
}

func (x *RequestTime) GetFromTime() *timestamppb.Timestamp {
	if x != nil {
		return x.FromTime
	}
	return nil
}

func (x *RequestTime) GetToTime() *timestamppb.Timestamp {
	if x != nil {
		return x.ToTime
	}
	return nil
}

type ListContractRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *IncludeExcludeInt32   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StudentCode   *IncludeExcludeString  `protobuf:"bytes,2,opt,name=student_code,json=studentCode,proto3" json:"student_code,omitempty"`
	FirstName     *IncludeExcludeString  `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      *IncludeExcludeString  `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	MiddleName    *IncludeExcludeString  `protobuf:"bytes,5,opt,name=middle_name,json=middleName,proto3" json:"middle_name,omitempty"`
	Email         *IncludeExcludeString  `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Phone         *IncludeExcludeString  `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	Gender        *IncludeExcludeUint32  `protobuf:"bytes,8,opt,name=gender,proto3" json:"gender,omitempty"`
	Address       *IncludeExcludeString  `protobuf:"bytes,9,opt,name=address,proto3" json:"address,omitempty"`
	RoomId        *IncludeExcludeString  `protobuf:"bytes,10,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	IsActive      *bool                  `protobuf:"varint,11,opt,name=is_active,json=isActive,proto3,oneof" json:"is_active,omitempty"`
	Sign          *IncludeExcludeString  `protobuf:"bytes,12,opt,name=sign,proto3" json:"sign,omitempty"`
	RegistryAt    *RequestTime           `protobuf:"bytes,13,opt,name=registry_at,json=registryAt,proto3" json:"registry_at,omitempty"`
	Total         uint32                 `protobuf:"varint,14,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContractRequest) Reset() {
	*x = ListContractRequest{}
	mi := &file_contract_contract_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContractRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContractRequest) ProtoMessage() {}

func (x *ListContractRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_contract_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContractRequest.ProtoReflect.Descriptor instead.
func (*ListContractRequest) Descriptor() ([]byte, []int) {
	return file_contract_contract_proto_rawDescGZIP(), []int{13}
}

func (x *ListContractRequest) GetId() *IncludeExcludeInt32 {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *ListContractRequest) GetStudentCode() *IncludeExcludeString {
	if x != nil {
		return x.StudentCode
	}
	return nil
}

func (x *ListContractRequest) GetFirstName() *IncludeExcludeString {
	if x != nil {
		return x.FirstName
	}
	return nil
}

func (x *ListContractRequest) GetLastName() *IncludeExcludeString {
	if x != nil {
		return x.LastName
	}
	return nil
}

func (x *ListContractRequest) GetMiddleName() *IncludeExcludeString {
	if x != nil {
		return x.MiddleName
	}
	return nil
}

func (x *ListContractRequest) GetEmail() *IncludeExcludeString {
	if x != nil {
		return x.Email
	}
	return nil
}

func (x *ListContractRequest) GetPhone() *IncludeExcludeString {
	if x != nil {
		return x.Phone
	}
	return nil
}

func (x *ListContractRequest) GetGender() *IncludeExcludeUint32 {
	if x != nil {
		return x.Gender
	}
	return nil
}

func (x *ListContractRequest) GetAddress() *IncludeExcludeString {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *ListContractRequest) GetRoomId() *IncludeExcludeString {
	if x != nil {
		return x.RoomId
	}
	return nil
}

func (x *ListContractRequest) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

func (x *ListContractRequest) GetSign() *IncludeExcludeString {
	if x != nil {
		return x.Sign
	}
	return nil
}

func (x *ListContractRequest) GetRegistryAt() *RequestTime {
	if x != nil {
		return x.RegistryAt
	}
	return nil
}

func (x *ListContractRequest) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ListContractReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contract      []*Contract            `protobuf:"bytes,1,rep,name=contract,proto3" json:"contract,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContractReply) Reset() {
	*x = ListContractReply{}
	mi := &file_contract_contract_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContractReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContractReply) ProtoMessage() {}

func (x *ListContractReply) ProtoReflect() protoreflect.Message {
	mi := &file_contract_contract_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContractReply.ProtoReflect.Descriptor instead.
func (*ListContractReply) Descriptor() ([]byte, []int) {
	return file_contract_contract_proto_rawDescGZIP(), []int{14}
}

func (x *ListContractReply) GetContract() []*Contract {
	if x != nil {
		return x.Contract
	}
	return nil
}

func (x *ListContractReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Sign          string                 `protobuf:"bytes,2,opt,name=sign,proto3" json:"sign,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignRequest) Reset() {
	*x = SignRequest{}
	mi := &file_contract_contract_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignRequest) ProtoMessage() {}

func (x *SignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_contract_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignRequest.ProtoReflect.Descriptor instead.
func (*SignRequest) Descriptor() ([]byte, []int) {
	return file_contract_contract_proto_rawDescGZIP(), []int{15}
}

func (x *SignRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SignRequest) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

type SignReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignReply) Reset() {
	*x = SignReply{}
	mi := &file_contract_contract_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignReply) ProtoMessage() {}

func (x *SignReply) ProtoReflect() protoreflect.Message {
	mi := &file_contract_contract_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignReply.ProtoReflect.Descriptor instead.
func (*SignReply) Descriptor() ([]byte, []int) {
	return file_contract_contract_proto_rawDescGZIP(), []int{16}
}

func (x *SignReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListTotalContractEachRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        uint32                 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTotalContractEachRoomRequest) Reset() {
	*x = ListTotalContractEachRoomRequest{}
	mi := &file_contract_contract_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTotalContractEachRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTotalContractEachRoomRequest) ProtoMessage() {}

func (x *ListTotalContractEachRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_contract_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTotalContractEachRoomRequest.ProtoReflect.Descriptor instead.
func (*ListTotalContractEachRoomRequest) Descriptor() ([]byte, []int) {
	return file_contract_contract_proto_rawDescGZIP(), []int{17}
}

func (x *ListTotalContractEachRoomRequest) GetNumber() uint32 {
	if x != nil {
		return x.Number
	}
	return 0
}

type ListTotalContractEachRoomReply struct {
	state            protoimpl.MessageState                             `protogen:"open.v1"`
	ContractEachRoom []*ListTotalContractEachRoomReply_ContractEachRoom `protobuf:"bytes,1,rep,name=contractEachRoom,proto3" json:"contractEachRoom,omitempty"`
	Message          string                                             `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListTotalContractEachRoomReply) Reset() {
	*x = ListTotalContractEachRoomReply{}
	mi := &file_contract_contract_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTotalContractEachRoomReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTotalContractEachRoomReply) ProtoMessage() {}

func (x *ListTotalContractEachRoomReply) ProtoReflect() protoreflect.Message {
	mi := &file_contract_contract_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTotalContractEachRoomReply.ProtoReflect.Descriptor instead.
func (*ListTotalContractEachRoomReply) Descriptor() ([]byte, []int) {
	return file_contract_contract_proto_rawDescGZIP(), []int{18}
}

func (x *ListTotalContractEachRoomReply) GetContractEachRoom() []*ListTotalContractEachRoomReply_ContractEachRoom {
	if x != nil {
		return x.ContractEachRoom
	}
	return nil
}

func (x *ListTotalContractEachRoomReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListTotalContractEachRoomReply_ContractEachRoom struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomId        string                 `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Total         uint32                 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTotalContractEachRoomReply_ContractEachRoom) Reset() {
	*x = ListTotalContractEachRoomReply_ContractEachRoom{}
	mi := &file_contract_contract_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTotalContractEachRoomReply_ContractEachRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTotalContractEachRoomReply_ContractEachRoom) ProtoMessage() {}

func (x *ListTotalContractEachRoomReply_ContractEachRoom) ProtoReflect() protoreflect.Message {
	mi := &file_contract_contract_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTotalContractEachRoomReply_ContractEachRoom.ProtoReflect.Descriptor instead.
func (*ListTotalContractEachRoomReply_ContractEachRoom) Descriptor() ([]byte, []int) {
	return file_contract_contract_proto_rawDescGZIP(), []int{18, 0}
}

func (x *ListTotalContractEachRoomReply_ContractEachRoom) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *ListTotalContractEachRoomReply_ContractEachRoom) GetTotal() uint32 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_contract_contract_proto protoreflect.FileDescriptor

const file_contract_contract_proto_rawDesc = "" +
	"\n" +
	"\x17contract/contract.proto\x12\fapi.contract\x1a\x1cgoogle/api/annotations.proto\x1a\x17validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8a\x05\n" +
	"\bContract\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x05B\a\xfaB\x04\x1a\x02(\x01R\x02id\x12+\n" +
	"\fstudent_code\x18\x02 \x01(\tB\b\xfaB\x05r\x03\x98\x01\n" +
	"R\vstudentCode\x121\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tB\x12\xfaB\x0fr\r2\v^[A-Za-z]+$R\tfirstName\x12/\n" +
	"\tlast_name\x18\x04 \x01(\tB\x12\xfaB\x0fr\r2\v^[A-Za-z]+$R\blastName\x123\n" +
	"\vmiddle_name\x18\x05 \x01(\tB\x12\xfaB\x0fr\r2\v^[A-Za-z]+$R\n" +
	"middleName\x12\x1d\n" +
	"\x05email\x18\x06 \x01(\tB\a\xfaB\x04r\x02`\x01R\x05email\x12\x1e\n" +
	"\x05phone\x18\a \x01(\tB\b\xfaB\x05r\x03\x98\x01\n" +
	"R\x05phone\x12\x1f\n" +
	"\x06gender\x18\b \x01(\rB\a\xfaB\x04*\x02(\x00R\x06gender\x12,\n" +
	"\x03dob\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x03dob\x12\x18\n" +
	"\aaddress\x18\n" +
	" \x01(\tR\aaddress\x12\x16\n" +
	"\x06avatar\x18\v \x01(\tR\x06avatar\x123\n" +
	"\aroom_id\x18\f \x01(\tB\x1a\xfaB\x17r\x152\x13^([A-Z])([0-9]{4}$)R\x06roomId\x12\x1b\n" +
	"\tis_active\x18\r \x01(\bR\bisActive\x12\x12\n" +
	"\x04sign\x18\x0e \x01(\tR\x04sign\x12;\n" +
	"\vregistry_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"registryAt\x12<\n" +
	"\x15notification_channels\x18\x10 \x01(\rB\a\xfaB\x04*\x02(\x00R\x14notificationChannels\"\xc1\x04\n" +
	"\x15CreateContractRequest\x12+\n" +
	"\fstudent_code\x18\x01 \x01(\tB\b\xfaB\x05r\x03\x98\x01\n" +
	"R\vstudentCode\x121\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tB\x12\xfaB\x0fr\r2\v^[A-Za-z]+$R\tfirstName\x12/\n" +
	"\tlast_name\x18\x03 \x01(\tB\x12\xfaB\x0fr\r2\v^[A-Za-z]+$R\blastName\x123\n" +
	"\vmiddle_name\x18\x04 \x01(\tB\x12\xfaB\x0fr\r2\v^[A-Za-z]+$R\n" +
	"middleName\x12\x1d\n" +
	"\x05email\x18\x05 \x01(\tB\a\xfaB\x04r\x02`\x01R\x05email\x12\x1e\n" +
	"\x05phone\x18\x06 \x01(\tB\b\xfaB\x05r\x03\x98\x01\n" +
	"R\x05phone\x12\x1f\n" +
	"\x06gender\x18\a \x01(\rB\a\xfaB\x04*\x02(\x00R\x06gender\x12,\n" +
	"\x03dob\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x03dob\x12\x18\n" +
	"\aaddress\x18\t \x01(\tR\aaddress\x12\x16\n" +
	"\x06avatar\x18\n" +
	" \x01(\tR\x06avatar\x123\n" +
	"\aroom_id\x18\v \x01(\tB\x1a\xfaB\x17r\x152\x13^([A-Z])([0-9]{4}$)R\x06roomId\x12\x1b\n" +
	"\tis_active\x18\f \x01(\bR\bisActive\x12\x12\n" +
	"\x04sign\x18\r \x01(\tR\x04sign\x12<\n" +
	"\x15notification_channels\x18\x0e \x01(\rB\a\xfaB\x04*\x02(\x00R\x14notificationChannels\"/\n" +
	"\x13CreateContractReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xcc\x06\n" +
	"\x15UpdateContractRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x05B\a\xfaB\x04\x1a\x02(\x01R\x02id\x120\n" +
	"\fstudent_code\x18\x02 \x01(\tB\b\xfaB\x05r\x03\x98\x01\n" +
	"H\x00R\vstudentCode\x88\x01\x01\x126\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tB\x12\xfaB\x0fr\r2\v^[A-Za-z]+$H\x01R\tfirstName\x88\x01\x01\x124\n" +
	"\tlast_name\x18\x04 \x01(\tB\x12\xfaB\x0fr\r2\v^[A-Za-z]+$H\x02R\blastName\x88\x01\x01\x128\n" +
	"\vmiddle_name\x18\x05 \x01(\tB\x12\xfaB\x0fr\r2\v^[A-Za-z]+$H\x03R\n" +
	"middleName\x88\x01\x01\x12\"\n" +
	"\x05email\x18\x06 \x01(\tB\a\xfaB\x04r\x02`\x01H\x04R\x05email\x88\x01\x01\x12#\n" +
	"\x05phone\x18\a \x01(\tB\b\xfaB\x05r\x03\x98\x01\n" +
	"H\x05R\x05phone\x88\x01\x01\x12$\n" +
	"\x06gender\x18\b \x01(\rB\a\xfaB\x04*\x02(\x00H\x06R\x06gender\x88\x01\x01\x12,\n" +
	"\x03dob\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x03dob\x12\x1d\n" +
	"\aaddress\x18\n" +
	" \x01(\tH\aR\aaddress\x88\x01\x01\x12\x1b\n" +
	"\x06avatar\x18\v \x01(\tH\bR\x06avatar\x88\x01\x01\x128\n" +
	"\aroom_id\x18\f \x01(\tB\x1a\xfaB\x17r\x152\x13^([A-Z])([0-9]{4}$)H\tR\x06roomId\x88\x01\x01\x12 \n" +
	"\tis_active\x18\r \x01(\bH\n" +
	"R\bisActive\x88\x01\x01\x12\x17\n" +
	"\x04sign\x18\x0e \x01(\tH\vR\x04sign\x88\x01\x01\x12A\n" +
	"\x15notification_channels\x18\x0f \x01(\rB\a\xfaB\x04*\x02(\x00H\fR\x14notificationChannels\x88\x01\x01B\x0f\n" +
	"\r_student_codeB\r\n" +
	"\v_first_nameB\f\n" +
	"\n" +
	"_last_nameB\x0e\n" +
	"\f_middle_nameB\b\n" +
	"\x06_emailB\b\n" +
	"\x06_phoneB\t\n" +
	"\a_genderB\n" +
	"\n" +
	"\b_addressB\t\n" +
	"\a_avatarB\n" +
	"\n" +
	"\b_room_idB\f\n" +
	"\n" +
	"_is_activeB\a\n" +
	"\x05_signB\x18\n" +
	"\x16_notification_channels\"/\n" +
	"\x13UpdateContractReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"0\n" +
	"\x15DeleteContractRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x05B\a\xfaB\x04\x1a\x02(\x01R\x02id\"/\n" +
	"\x13DeleteContractReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"-\n" +
	"\x12GetContractRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x05B\a\xfaB\x04\x1a\x02(\x01R\x02id\"`\n" +
	"\x10GetContractReply\x122\n" +
	"\bcontract\x18\x01 \x01(\v2\x16.api.contract.ContractR\bcontract\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"b\n" +
	"\x14IncludeExcludeString\x12$\n" +
	"\bincludes\x18\x01 \x03(\tB\b\xfaB\x05\x92\x01\x02\x18\x01R\bincludes\x12$\n" +
	"\bexcludes\x18\x02 \x03(\tB\b\xfaB\x05\x92\x01\x02\x18\x01R\bexcludes\"b\n" +
	"\x14IncludeExcludeUint32\x12$\n" +
	"\bincludes\x18\x01 \x03(\rB\b\xfaB\x05\x92\x01\x02\x18\x01R\bincludes\x12$\n" +
	"\bexcludes\x18\x02 \x03(\rB\b\xfaB\x05\x92\x01\x02\x18\x01R\bexcludes\"a\n" +
	"\x13IncludeExcludeInt32\x12$\n" +
	"\bincludes\x18\x01 \x03(\x05B\b\xfaB\x05\x92\x01\x02\x18\x01R\bincludes\x12$\n" +
	"\bexcludes\x18\x02 \x03(\x05B\b\xfaB\x05\x92\x01\x02\x18\x01R\bexcludes\"{\n" +
	"\vRequestTime\x127\n" +
	"\tfrom_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\bfromTime\x123\n" +
	"\ato_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x06toTime\"\xbd\x06\n" +
	"\x13ListContractRequest\x121\n" +
	"\x02id\x18\x01 \x01(\v2!.api.contract.IncludeExcludeInt32R\x02id\x12E\n" +
	"\fstudent_code\x18\x02 \x01(\v2\".api.contract.IncludeExcludeStringR\vstudentCode\x12A\n" +
	"\n" +
	"first_name\x18\x03 \x01(\v2\".api.contract.IncludeExcludeStringR\tfirstName\x12?\n" +
	"\tlast_name\x18\x04 \x01(\v2\".api.contract.IncludeExcludeStringR\blastName\x12C\n" +
	"\vmiddle_name\x18\x05 \x01(\v2\".api.contract.IncludeExcludeStringR\n" +
	"middleName\x128\n" +
	"\x05email\x18\x06 \x01(\v2\".api.contract.IncludeExcludeStringR\x05email\x128\n" +
	"\x05phone\x18\a \x01(\v2\".api.contract.IncludeExcludeStringR\x05phone\x12:\n" +
	"\x06gender\x18\b \x01(\v2\".api.contract.IncludeExcludeUint32R\x06gender\x12<\n" +
	"\aaddress\x18\t \x01(\v2\".api.contract.IncludeExcludeStringR\aaddress\x12;\n" +
	"\aroom_id\x18\n" +
	" \x01(\v2\".api.contract.IncludeExcludeStringR\x06roomId\x12 \n" +
	"\tis_active\x18\v \x01(\bH\x00R\bisActive\x88\x01\x01\x126\n" +
	"\x04sign\x18\f \x01(\v2\".api.contract.IncludeExcludeStringR\x04sign\x12:\n" +
	"\vregistry_at\x18\r \x01(\v2\x19.api.contract.RequestTimeR\n" +
	"registryAt\x12\x14\n" +
	"\x05total\x18\x0e \x01(\rR\x05totalB\f\n" +
	"\n" +
	"_is_active\"a\n" +
	"\x11ListContractReply\x122\n" +
	"\bcontract\x18\x01 \x03(\v2\x16.api.contract.ContractR\bcontract\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\":\n" +
	"\vSignRequest\x12\x17\n" +
	"\x02id\x18\x01 \x01(\x05B\a\xfaB\x04\x1a\x02(\x01R\x02id\x12\x12\n" +
	"\x04sign\x18\x02 \x01(\tR\x04sign\"%\n" +
	"\tSignReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\":\n" +
	" ListTotalContractEachRoomRequest\x12\x16\n" +
	"\x06number\x18\x01 \x01(\rR\x06number\"\xe8\x01\n" +
	"\x1eListTotalContractEachRoomReply\x12i\n" +
	"\x10contractEachRoom\x18\x01 \x03(\v2=.api.contract.ListTotalContractEachRoomReply.ContractEachRoomR\x10contractEachRoom\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x1aA\n" +
	"\x10ContractEachRoom\x12\x17\n" +
	"\aroom_id\x18\x01 \x01(\tR\x06roomId\x12\x14\n" +
	"\x05total\x18\x02 \x01(\rR\x05total2\x83\x05\n" +
	"\x0fContractService\x12X\n" +
	"\x0eCreateContract\x12#.api.contract.CreateContractRequest\x1a!.api.contract.CreateContractReply\x12X\n" +
	"\x0eUpdateContract\x12#.api.contract.UpdateContractRequest\x1a!.api.contract.UpdateContractReply\x12B\n" +
	"\fSignContract\x12\x19.api.contract.SignRequest\x1a\x17.api.contract.SignReply\x12X\n" +
	"\x0eDeleteContract\x12#.api.contract.DeleteContractRequest\x1a!.api.contract.DeleteContractReply\x12O\n" +
	"\vGetContract\x12 .api.contract.GetContractRequest\x1a\x1e.api.contract.GetContractReply\x12R\n" +
	"\fListContract\x12!.api.contract.ListContractRequest\x1a\x1f.api.contract.ListContractReply\x12y\n" +
	"\x19ListTotalContractEachRoom\x12..api.contract.ListTotalContractEachRoomRequest\x1a,.api.contract.ListTotalContractEachRoomReplyB\x17Z\x15/contractApi;contractb\x06proto3"

var (
	file_contract_contract_proto_rawDescOnce sync.Once
	file_contract_contract_proto_rawDescData []byte
)

func file_contract_contract_proto_rawDescGZIP() []byte {
	file_contract_contract_proto_rawDescOnce.Do(func() {
		file_contract_contract_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contract_contract_proto_rawDesc), len(file_contract_contract_proto_rawDesc)))
	})
	return file_contract_contract_proto_rawDescData
}

var file_contract_contract_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_contract_contract_proto_goTypes = []any{
	(*Contract)(nil),                                        // 0: api.contract.Contract
	(*CreateContractRequest)(nil),                           // 1: api.contract.CreateContractRequest
	(*CreateContractReply)(nil),                             // 2: api.contract.CreateContractReply
	(*UpdateContractRequest)(nil),                           // 3: api.contract.UpdateContractRequest
	(*UpdateContractReply)(nil),                             // 4: api.contract.UpdateContractReply
	(*DeleteContractRequest)(nil),                           // 5: api.contract.DeleteContractRequest
	(*DeleteContractReply)(nil),                             // 6: api.contract.DeleteContractReply
	(*GetContractRequest)(nil),                              // 7: api.contract.GetContractRequest
	(*GetContractReply)(nil),                                // 8: api.contract.GetContractReply
	(*IncludeExcludeString)(nil),                            // 9: api.contract.IncludeExcludeString
	(*IncludeExcludeUint32)(nil),                            // 10: api.contract.IncludeExcludeUint32
	(*IncludeExcludeInt32)(nil),                             // 11: api.contract.IncludeExcludeInt32
	(*RequestTime)(nil),                                     // 12: api.contract.RequestTime
	(*ListContractRequest)(nil),                             // 13: api.contract.ListContractRequest
	(*ListContractReply)(nil),                               // 14: api.contract.ListContractReply
	(*SignRequest)(nil),                                     // 15: api.contract.SignRequest
	(*SignReply)(nil),                                       // 16: api.contract.SignReply
	(*ListTotalContractEachRoomRequest)(nil),                // 17: api.contract.ListTotalContractEachRoomRequest
	(*ListTotalContractEachRoomReply)(nil),                  // 18: api.contract.ListTotalContractEachRoomReply
	(*ListTotalContractEachRoomReply_ContractEachRoom)(nil), // 19: api.contract.ListTotalContractEachRoomReply.ContractEachRoom
	(*timestamppb.Timestamp)(nil),                           // 20: google.protobuf.Timestamp
}
var file_contract_contract_proto_depIdxs = []int32{
	20, // 0: api.contract.Contract.dob:type_name -> google.protobuf.Timestamp
	20, // 1: api.contract.Contract.registry_at:type_name -> google.protobuf.Timestamp
	20, // 2: api.contract.CreateContractRequest.dob:type_name -> google.protobuf.Timestamp
	20, // 3: api.contract.UpdateContractRequest.dob:type_name -> google.protobuf.Timestamp
	0,  // 4: api.contract.GetContractReply.contract:type_name -> api.contract.Contract
	20, // 5: api.contract.RequestTime.from_time:type_name -> google.protobuf.Timestamp
	20, // 6: api.contract.RequestTime.to_time:type_name -> google.protobuf.Timestamp
	11, // 7: api.contract.ListContractRequest.id:type_name -> api.contract.IncludeExcludeInt32
	9,  // 8: api.contract.ListContractRequest.student_code:type_name -> api.contract.IncludeExcludeString
	9,  // 9: api.contract.ListContractRequest.first_name:type_name -> api.contract.IncludeExcludeString
	9,  // 10: api.contract.ListContractRequest.last_name:type_name -> api.contract.IncludeExcludeString
	9,  // 11: api.contract.ListContractRequest.middle_name:type_name -> api.contract.IncludeExcludeString
	9,  // 12: api.contract.ListContractRequest.email:type_name -> api.contract.IncludeExcludeString
	9,  // 13: api.contract.ListContractRequest.phone:type_name -> api.contract.IncludeExcludeString
	10, // 14: api.contract.ListContractRequest.gender:type_name -> api.contract.IncludeExcludeUint32
	9,  // 15: api.contract.ListContractRequest.address:type_name -> api.contract.IncludeExcludeString
	9,  // 16: api.contract.ListContractRequest.room_id:type_name -> api.contract.IncludeExcludeString
	9,  // 17: api.contract.ListContractRequest.sign:type_name -> api.contract.IncludeExcludeString
	12, // 18: api.contract.ListContractRequest.registry_at:type_name -> api.contract.RequestTime
	0,  // 19: api.contract.ListContractReply.contract:type_name -> api.contract.Contract
	19, // 20: api.contract.ListTotalContractEachRoomReply.contractEachRoom:type_name -> api.contract.ListTotalContractEachRoomReply.ContractEachRoom
	1,  // 21: api.contract.ContractService.CreateContract:input_type -> api.contract.CreateContractRequest
	3,  // 22: api.contract.ContractService.UpdateContract:input_type -> api.contract.UpdateContractRequest
	15, // 23: api.contract.ContractService.SignContract:input_type -> api.contract.SignRequest
	5,  // 24: api.contract.ContractService.DeleteContract:input_type -> api.contract.DeleteContractRequest
	7,  // 25: api.contract.ContractService.GetContract:input_type -> api.contract.GetContractRequest
	13, // 26: api.contract.ContractService.ListContract:input_type -> api.contract.ListContractRequest
	17, // 27: api.contract.ContractService.ListTotalContractEachRoom:input_type -> api.contract.ListTotalContractEachRoomRequest
	2,  // 28: api.contract.ContractService.CreateContract:output_type -> api.contract.CreateContractReply
	4,  // 29: api.contract.ContractService.UpdateContract:output_type -> api.contract.UpdateContractReply
	16, // 30: api.contract.ContractService.SignContract:output_type -> api.contract.SignReply
	6,  // 31: api.contract.ContractService.DeleteContract:output_type -> api.contract.DeleteContractReply
	8,  // 32: api.contract.ContractService.GetContract:output_type -> api.contract.GetContractReply
	14, // 33: api.contract.ContractService.ListContract:output_type -> api.contract.ListContractReply
	18, // 34: api.contract.ContractService.ListTotalContractEachRoom:output_type -> api.contract.ListTotalContractEachRoomReply
	28, // [28:35] is the sub-list for method output_type
	21, // [21:28] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_contract_contract_proto_init() }
func file_contract_contract_proto_init() {
	if File_contract_contract_proto != nil {
		return
	}
	file_contract_contract_proto_msgTypes[3].OneofWrappers = []any{}
	file_contract_contract_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contract_contract_proto_rawDesc), len(file_contract_contract_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contract_contract_proto_goTypes,
		DependencyIndexes: file_contract_contract_proto_depIdxs,
		MessageInfos:      file_contract_contract_proto_msgTypes,
	}.Build()
	File_contract_contract_proto = out.File
	file_contract_contract_proto_goTypes = nil
	file_contract_contract_proto_depIdxs = nil
}
