// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ContractsColumns holds the columns for the "contracts" table.
	ContractsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "student_code", Type: field.TypeString, Size: 10},
		{Name: "first_name", Type: field.TypeString, Size: 128},
		{Name: "last_name", Type: field.TypeString, Size: 128},
		{Name: "middle_name", Type: field.TypeString, Size: 128},
		{Name: "email", Type: field.TypeString, Size: 128},
		{Name: "sign", Type: field.TypeString, Size: 128},
		{Name: "phone", Type: field.TypeString, Size: 10},
		{Name: "gender", Type: field.TypeUint8},
		{Name: "dob", Type: field.TypeTime, Nullable: true},
		{Name: "address", Type: field.TypeString},
		{Name: "avatar", Type: field.TypeBytes},
		{Name: "is_active", Type: field.TypeBool, Default: false},
		{Name: "registry_at", Type: field.TypeTime},
		{Name: "room_id", Type: field.TypeString, Size: 5},
		{Name: "notification_channels", Type: field.TypeUint8},
	}
	// ContractsTable holds the schema information for the "contracts" table.
	ContractsTable = &schema.Table{
		Name:       "contracts",
		Columns:    ContractsColumns,
		PrimaryKey: []*schema.Column{ContractsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "contract_id",
				Unique:  true,
				Columns: []*schema.Column{ContractsColumns[0]},
			},
			{
				Name:    "contract_student_code",
				Unique:  false,
				Columns: []*schema.Column{ContractsColumns[1]},
			},
			{
				Name:    "contract_first_name_last_name",
				Unique:  false,
				Columns: []*schema.Column{ContractsColumns[2], ContractsColumns[3]},
				Annotation: &entsql.IndexAnnotation{
					PrefixColumns: map[string]uint{
						ContractsColumns[2].Name: 16,

						ContractsColumns[3].Name: 16,
					},
				},
			},
			{
				Name:    "contract_email",
				Unique:  false,
				Columns: []*schema.Column{ContractsColumns[5]},
			},
			{
				Name:    "contract_sign",
				Unique:  false,
				Columns: []*schema.Column{ContractsColumns[6]},
			},
			{
				Name:    "contract_phone",
				Unique:  false,
				Columns: []*schema.Column{ContractsColumns[7]},
			},
			{
				Name:    "contract_is_active",
				Unique:  false,
				Columns: []*schema.Column{ContractsColumns[12]},
			},
			{
				Name:    "contract_room_id",
				Unique:  false,
				Columns: []*schema.Column{ContractsColumns[14]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ContractsTable,
	}
)

func init() {
}
