server:
  http:
    addr: 0.0.0.0:8000
    timeout: 300s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 300s
data:
  database:
    driver: postgres
    username: chuong
    password: 4SPIn5wridRuxoml8LD
    host: 127.0.0.1
    port: "5432"
    dbname: postgres-db
    # The application (server) is local time
    params: "sslmode=disable&search_path=public"
    # Asia%2FHo_Chi_Minh, UTC, Local, Singapore
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
